#!/bin/bash

echo "====================================================================="
echo "  Deployment Guide for Docker-Kube-Demo Project"
echo "====================================================================="
echo ""
echo "This guide outlines the steps to update your Docker images and Helm"
echo "chart, and deploy changes to a Kubernetes cluster."
echo ""
echo "---------------------------------------------------------------------"
echo "  Step 1: Stop currently running Docker Compose services (if any)"
echo "---------------------------------------------------------------------"
echo "Before making changes, it's good practice to stop any locally running"
echo "Docker Compose services to avoid conflicts."
echo "Command: docker compose down"
echo ""
echo "---------------------------------------------------------------------"
echo "  Step 2: Make your code changes"
echo "---------------------------------------------------------------------"
echo "Edit your frontend code in the 'frontend/' directory or backend code"
echo "in the 'backend/' directory."
echo ""
echo "---------------------------------------------------------------------"
echo "  Step 3: Rebuild Docker Images"
echo "---------------------------------------------------------------------"
echo "After making changes, you need to rebuild the Docker images. This"
echo "ensures your latest code is packaged into the containers."
echo "Command: docker compose build"
echo ""
echo "---------------------------------------------------------------------"
echo "  Step 4: Test Locally with Docker Compose"
echo "---------------------------------------------------------------------"
echo "It's highly recommended to test your changes locally before deploying"
echo "to Kubernetes. This will start your services using the newly built"
echo "images."
echo "Command: docker compose up -d"
echo "Access frontend at: http://localhost:8501"
echo "Access backend at: http://localhost:8000"
echo "To stop local services: docker compose down"
echo ""
echo "---------------------------------------------------------------------"
echo "  Step 5: Push Docker Images to a Registry (if deploying to K8s)"
echo "---------------------------------------------------------------------"
echo "If you plan to deploy to a Kubernetes cluster, you'll need to push"
echo "your Docker images to a container registry (e.g., Docker Hub, GCR)."
echo "Replace 'your-dockerhub-username' with your actual username."
echo "Command for backend: docker tag docker-kube-demo-backend your-dockerhub-username/docker-kube-demo-backend:latest"
echo "Command for backend: docker push your-dockerhub-username/docker-kube-demo-backend:latest"
echo "Command for frontend: docker tag docker-kube-demo-frontend your-dockerhub-username/docker-kube-demo-frontend:latest"
echo "Command for frontend: docker push your-dockerhub-username/docker-kube-demo-frontend:latest"
echo ""
echo "---------------------------------------------------------------------"
echo "  Step 6: Update Helm Chart Values (if necessary)"
echo "---------------------------------------------------------------------"
echo "If you pushed to a different registry or changed image tags, update"
echo "the 'helm/docker-kube-demo/values.yaml' file accordingly."
echo "Example: Update 'backend.image.repository' and 'frontend.image.repository'"
echo "         to 'your-dockerhub-username/docker-kube-demo-backend' and"
echo "         'your-dockerhub-username/docker-kube-demo-demo-frontend' respectively."
echo ""
echo "---------------------------------------------------------------------"
echo "  Step 7: Deploy/Upgrade to Kubernetes using Helm"
echo "---------------------------------------------------------------------"
echo "Once your images are in a registry and your Helm values are updated,"
echo "you can deploy or upgrade your application on Kubernetes."
echo "First, ensure your Kubernetes context is set correctly."
echo "To install for the first time: helm install docker-kube-demo ./helm/docker-kube-demo"
echo "To upgrade an existing release: helm upgrade docker-kube-demo ./helm/docker-kube-demo"
echo ""
echo "---------------------------------------------------------------------"
echo "  Step 8: Verify Deployment on Kubernetes"
echo "---------------------------------------------------------------------"
echo "Check the status of your pods and services."
echo "Command: kubectl get pods"
echo "Command: kubectl get services"
echo "You can get the external IP for the frontend service (if LoadBalancer is used):"
echo "Command: kubectl get service docker-kube-demo-frontend"
echo ""
echo "====================================================================="
echo "  End of Deployment Guide"
echo "====================================================================="
