apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-kube-demo.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "docker-kube-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
  selector:
    {{- include "docker-kube-demo.selectorLabels" . | nindent 4 }}
